### ISSUE TITLE
Some questions related to the paper

### ISSUE THREAD

**Issue by JIANG-CX** [intel/ndg-fitting#7]
Wonderful work! While reading the paper, I encountered some confusion. In section 3.3, Practical Observations, it states, "In our scheme, the iterative optimization is responsible for driving any added capacity of the representation into the right direction." I am curious about why the scheme used in this work can drive the added capacity into the right direction. Thank you.

**Comment by diolatzis** [comment]
Hi, I am glad you liked our work. The statement is related to our densification system where the low impact child Gaussians are introduced and it is up to the optimizer to choose where to use them. Once the optimizer has already started to make use of them by increasing their opacity/brightness they materialize, i.e. the introduced capacity is already improving the quality of the image. Hope this clarifies it.

**Comment by JIANG-CX** [comment]
Thanks for your reply.
