### ISSUE TITLE
Reproduce of NeX datasets

### ISSUE THREAD

**Issue by Gaozhongpai** [intel/ndg-fitting#8]
Hi, I'm using the default code to run the shiny dataset from NeX (resolutions of 1008 x 567 or 1008 x 756), but the results seem lower than the numbers reported in the paper. Are there any parameters I should adjust to align with the reported performance? Thanks!

|        | PSNR  |  SSIM | # points |
|--------|-------|-------|----------|
| cd     | 17.98 | 0.530 | 120,536  |
| crest  | 11.87 | 0.122 | 42,440   |
| food   | 12.31 | 0.260 | 50,790   |
| giants | 14.72 | 0.300 | 39,117   |
| lab    | 19.00 | 0.552 | 90,896   |
| pasta  | 12.88 | 0.279 | 51,080   |
| seasoning | 14.06 | 0.425 | 41,665 |
| tools  | 11.17 | 0.461 | 51,842   |
| avg    | 14.25 | 0.366 | 61,046   |

**Comment by diolatzis** [comment]
Hi, hmm that is quite weird. I just cloned and ran the code and got 26.69 PSNR in the CD scene after 1k steps. Also the number of points seems to be quite low (I get 200k after 1k steps on CD). Can you provide some more information about your setup? Maybe the training curves and images? Can you also confirm you just ran 

`--dataset_path .\scenes\shiny\cd\ --tensorboard`

![train](https://github.com/user-attachments/assets/ee9ae326-4574-49d2-aa23-58e9fb145384)

**Comment by Gaozhongpai** [comment]
Thanks for the response. I will re-clone the project and re-run it tomorrow.

**Comment by Gaozhongpai** [comment]
@diolatzis Thank you, I've fixed the problem. In the NeX paper, images from the Shiny dataset are resized to a width of 1008 pixels. However, I had been resizing the images without adjusting the intrinsic camera parameters.
